### PR TITLE
updated webpack intergration config

### PR DESCRIPTION
**Pull request by tellxp**
add ['.min.js'] and comments, for some widgets using 'util/main', developers have to use src js for webpack

### CODE REVIEW

**Comment by underlog** [comment]
Thank you for the submission. I am not sure what you mean by the `src/js` destination, though. A non-working example would be great, since this seems like something that we should fix. Thanls!

**Comment by tellxp** [comment]
Hi Ivanov：

- extensions: [ '', '.js', 'min.js' ]

  - the document lost a ‘.’ Before min.js, so webpack can’t resolve .min.js file in kendo/dist/js, and you'll get `Module not found: Error: Cannot resolve module 'kendo.draganddrop'`.

- For kendo pro (commercial) developers

  - if you want to use grid widget(or kendo.dataviz.*, kendo.drawing, kendo.gantt, kendo.pdf...), so you require(‘kendo.grid’) in head of your js file, webpack can't resolve util/main, and you'll get `ERROR in ./library/kendo/dist/js/kendo.grid.min.js
Module not found: Error: Cannot resolve module 'util/main'`

- In order to solve these error, i got a config, which include css-loader and font-loader:

```javascript
var path = require('path');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
module.exports = {
    resolve: {
        extensions: [ '', '.js', '.min.js' ],
        root: [
            path.resolve('.'),
            path.resolve('./library/kendo/src/js/')
        ]
    },
    entry: {
        index: './src/scripts/index'
    },
    devtool: "#source-map",
    output: {
        path:'./src',
        filename: './bundle.js'
    },

    module: {
        loaders: [
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract(
                    "style-loader",
                    "css-loader"
                )
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader")
            },
            {
                test: /\.html$/,
                loader: 'file?name=views/[name].[ext]'
            },
            {
                test: /\.(png|jpg|gif)$/,
                loader:'file?name=./styles/images/[name].[ext]'
            },
            {
                test: /\.woff(\?[\s\S]+)?$/,
                loader: 'file?name=./styles/fonts/[name].[ext]'
            },
            {
                test: /\.woff2(\?[\s\S]+)?$/,
                loader: 'file?name=./styles/fonts/[name].[ext]'
            },
            {
                test: /\.ttf(\?[\s\S]+)?$/,
                loader: 'file?name=./styles/fonts/[name].[ext]'
            },
            {
                test: /\.eot(\?[\s\S]+)?$/,
                loader: 'file?name=./styles/fonts/[name].[ext]'
            },
            {
                test: /\.svg(\?[\s\S]+)?$/,
                loader: 'file?name=./styles/fonts/[name].[ext]'
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin("./bundle.css", {
            disable: false,
            allChunks: true
        })
    ]
}
```

**Comment by underlog** [comment]
I get the first part (the missing dot). 

However, the second does not seem right. The grid file includes the named module "util/main". One should not need to resort to `src/js/` as a source folder. If this is so, then this seems like a bug on our side. I have to reproduce it on my side in order to say more.

**Comment by tellxp** [comment]
Actually, I don't konw why. I thought min.js would work fine. However, I got the util/main error.
After change to src, everything works fine.

**Comment by Crevil** [comment]
We hit the issue with the module 'util/main' as well to day.
We loaded kendo professional from the folder `kendo/js` and the minifed files.
After changing to the source files in `kendo/src/js` this was resolved.

**Comment by underlog** [comment]
Hi guys,  

given that you are using webpack, you may benefit greatly from the NPM distribution channel. Please check this help article - http://docs.telerik.com/kendo-ui/intro/installation/npm .

**Comment by Crevil** [comment]
Can we expect a production stable solution when using the NPM package with Git endpoint for the professional solution?

**Comment by underlog** [comment]
This is basically the same service we use for Bower, which people are using for quite a while. Like the docs suggest, that we are in the process of moving to a private NPM registry server, which will supersede the current solution.

**Comment by Crevil** [comment]
Thank you for the clarification. We will look into this.

**Pull request closed without merging**
