### PR TITLE
Support jQuery.noConflict mode for Kendo message

### PR DESCRIPTION
**Pull request by pascalberger**
Currently the Kendo message files don't work while jQuery is in noConflict mode. This PR used the window.kendo.jQuery object instead of $ for jQuery functions like everywhere else in the Kendo code.

### CODE REVIEW

**Comment by KirilNN** [comment]
Hi @pascalberger,

I can see that all the files are changed again. You can see all the changes from the pull request here:

https://github.com/iozag/kendo-ui-core/commit/d4bb2384a26d06a9c0a03a2e15a96cefe570b8c9

You can see that the whole files are changed.

**Comment by pascalberger** [comment]
Oh my. So I should ignore your contribution guidelines (Space indentation, size of 4)?

**Comment by KirilNN** [comment]
Hi @pascalberger,

I have just added the changes with the following commit b6a9e238f42ed5b0d01d3509c55eaf1211478b4c. Thanks again for the contribution.

**Comment by pascalberger** [comment]
Oh got it! Less identation more style difference between individual files and more JSHint errors for getting PRs merged :)

**Pull request closed without merging**
