### PR TITLE
Add a section on array formulas

### PR DESCRIPTION
**Pull request by dmihaylo**
Here's a suggestion for letting end users know about the adjacent-cell distribution of the resulting matrix values from array formulas. 

@tsvetomir @mishoo Guys, could you have a look and provide your feedback? Many thanks!

### CODE REVIEW

**Comment by tsvetomir** [comment]
I figured we'll be better off if we document it with all current limitations. Mihai, are we missing some?

**Comment by mishoo** [comment]
I added some clarifications, and removed the list of steps since it feels unnecessary.  @dmihaylo Feel free to modify it further.

**Comment by dmihaylo** [comment]
Thank you both! 
Added some final touches. Just let me know if a further review should be made.

**Comment by tsvetomir** [comment]
Looks good to me, thank you both!

**Pull request merged**
