### PR TITLE
Update kendo.messages.da-DK.js

### PR DESCRIPTION
**Pull request by ejvind**
Translated kendo.ui.Scheduler texts from English to Danish

### CODE REVIEW

**Comment by jesperronn** [comment]
:+1: Nice. PR #1130 takes care of the other parts, since I didnt use the scheduler. So this and #1130 will probably fit even without merge conflicts :)

**Comment by jesperronn** [comment]
@valchev could be nice if this and #1130 could be merged. Is there anything else you need in order to merge this?

**Comment by valchev** [comment]
Hello guys,
first of all let me apologize for the late reply.

@ejvind thank you for the contribution. Could you please read and sign the [Kendo UI Core Contribution License Agreement](http://www.telerik.com/kendo-ui/cla), to confirm you've read and acknowledged the legal aspects of your contributions.

Once the license agreement is signed we will immediately merge the provided translations.

**Comment by ejvind** [comment]
Hi Alexander. 
I've now signed the license agreement. 
Best regards 
Thomas Nørgaard 
Den 01/10/2015 09.53 skrev Alexander Valchev <notifications@github.com>:Hello guys,
first of all let me apologize for the late reply.

@ejvind thank you for the contribution. Could you please read and sign the Kendo UI Core Contribution License Agreement, to confirm you've read and acknowledged the legal aspects of your contributions.

Once the license agreement is signed we will immediately merge the provided translations.

**Pull request merged**
