### PR TITLE
Excel file extension typo

### PR DESCRIPTION
**Pull request by ppseafield**
s/xslx/xlsx/g

### CODE REVIEW

**Comment by VicTachev** [comment]
@ppseafield, Thank you for the fixed typo. In order for us to be able to merge the changes we need you to sign our [Contribution Agreement](https://docs.google.com/forms/d/e/1FAIpQLSduN9hHUJpnjr_KOGsmSM_yGO-KKKggCJhiaOlEOLig6_Wkbg/viewform)

**Comment by ppseafield** [comment]
@VicTachev Sure, I can do that, but first I'd like to know why you need my mailing address. :)

Also, as recommended by the Contribution Agreement I sent an email asking about the address requirement to KendoUICore@telerik.com which promptly bounced.

image

**Comment by VicTachev** [comment]
The current form is somewhat outdated and we are in the process of updating it. That said, we will not be sending you packages :)

**Comment by ppseafield** [comment]
I have signed the agreement.

**Review by VicTachev — APPROVED** [review]

**Pull request merged**
