### PR TITLE
updated french language ui.grid messages

### PR DESCRIPTION
**Pull request by sdudnic**

### CODE REVIEW

**Review by sdudnic — COMMENTED** [review]
please note the space in french language before ":" or "?" that is OK

**Comment by StoyanGoranov** [comment]
I propose continuing the communication related to the pull request here. In order to make it more straightforward. 

For your convenience I am sharing the [Kendo UI Core Contribution](https://docs.google.com/forms/d/e/1FAIpQLSduN9hHUJpnjr_KOGsmSM_yGO-KKKggCJhiaOlEOLig6_Wkbg/viewform) agreement once again. Please note that you have to sign it only once.

Please let me know once this is done to continue the review of this Pull Request.

**Comment by sdudnic** [comment]
> I propose continuing the communication related to the pull request here. In order to make it more straightforward.
> 
> For your convenience I am sharing the [Kendo UI Core Contribution](https://docs.google.com/forms/d/e/1FAIpQLSduN9hHUJpnjr_KOGsmSM_yGO-KKKggCJhiaOlEOLig6_Wkbg/viewform) agreement once again. Please note that you have to sign it only once.
> 
> Please let me know once this is done to continue the review of this Pull Request.

done

**Comment by sdudnic** [comment]
anything else to do?

**Review by VicTachev — APPROVED** [review]

**Review by StoyanGoranov — APPROVED** [review]

**Pull request merged**
