### PR TITLE
Migrate to github actions

### PR DESCRIPTION
**Pull request by joneff**
Part of telerik/kendo#11525

### CODE REVIEW

**Comment by joneff** [comment]
@tsvetomir after this is merged, we can safely remove travis integragtion

**Review by zdravkov — APPROVED** [review]

**Review by Iankodj — APPROVED** [review]

**Comment by joneff** [comment]
Supersedes #5848

**Review by ag-petrov — APPROVED** [review]

**Review by tsvetomir — APPROVED** [review]

**Review by ipeshev — COMMENTED** [review]
Do we need 'restore-keys' option , it may return node_modules not matching that package-lock.json, which file be overwritten ( eventually ) after next step `npm install`, so when package-lock.json file will be updated manually , on release , in same build  ?  cc. @tsonev @popov I'm ultimate fan of such recursive mechanics as long as they are simple and clear.

**Comment by joneff** [comment]
I am caching npm cache folder. Anything not found in it will be installed. As for the cache key: anytime a new package-lock is found, the cache will be busted, which seems like a reasonable thing to do.

**Comment by tsvetomir** [comment]
Caching the user `npm` folder doesn't seem risky. If that breaks, then it's surely an npm issue.

**Comment by joneff** [comment]
@ipeshev  you make a point about the restore keys -- they are not really needed. I will remove them.

**Comment by ipeshev** [comment]
@kendo-qa Something obscure is happening here with GH actions caching capabilities, for me the cleanest way begins with  `yarn install --flat` . It is terra incognita so we will see how this will evolve.

**Comment by tsvetomir** [comment]
Let's not get yarn into the picture just yet.

**Pull request merged**
