### PR TITLE
Arabic localized messages

### PR DESCRIPTION
**Pull request by ahmedatia**
Hello there!

I'm opening this PR to add Arabic translation of Kendo UI messages. Currently, the Arabic translation of Kendo UI messages is not available. This PR adds it to different Arabic cultures.

In reference to the Contributor License Agreement, this is to confirm that I already signed it.

Since this is the initial addition of the Arabic translation of all Kendo UI messages (as of the latest release), I would like to share a quick brief about the collaborative efforts between different parties to ensure the accuracy of translated messages as follows:

- The messages file has been translated by @MidooDj and his team at [UX Writing بالعربية](https://uxwritingar.com/)
- The translated messages were then reviewed @HossamBarakatBA
- It has been a while since we at [@BitzSecureNetworks](https://github.com/BitzSecureNetworks) are using the localized messages to ensure all is good before opening this PR.

I hope this helps. Let me know if you have questions.

### CODE REVIEW

**Comment by DaleyKD** [comment]
Can we try to get this pulled in soon?  We need this.

**Comment by MidooDj** [comment]
any new?

**Comment by MidooDj** [comment]
@DaleyKD 👀

**Comment by MidooDj** [comment]
@ahmedatia

**Comment by ag-petrov** [comment]
Thank you for the contribution!

**Pull request merged**
