### PR TITLE
Fix DateTimePicker when using ISO date format

### PR DESCRIPTION
**Pull request by Bemjamin**
The DateTimePicker does not parse the hour correctly because of the order of parseFormats. The most generic format ("yyyy-MM-dd") comes first into the array so the hour is never considered.

### CODE REVIEW

**Comment by ggkrustev** [comment]
Thanks for the head up and for the fix. I agree that ISO date with time will be ignored, which defeats the purpose of its usage in first place.

I will merge the fix right away!

**Comment by ggkrustev** [comment]
Hey @Bemjamin, could you sign our [CLA](https://docs.google.com/forms/d/18J7DY9QbaeIaCpyRwmN0iCubiCzRKlAz847hD6Pzgyw/viewform) for the sake of legitimacy.

**Comment by Bemjamin** [comment]
Hello @ggkrustev, it's signed

**Comment by ggkrustev** [comment]
Thanks!

**Pull request merged**
