### PR TITLE
Fix popup close without effects should hide wrapper #5326

### PR DESCRIPTION
**Pull request by nlazarov**
The bulk of changes in `tests/popup/popup.js` is due to the line endings and me using Windows.

### CODE REVIEW

**Comment by jivanova** [comment]
The fix seems okay for the kendo Editor. Please, close the [issue](https://github.com/telerik/kendo/issues/5326) once the pull request is approved.

**Comment by ggkrustev** [comment]
Hi @nlazarov,

As far as I understand the fix, we will need to close the popup element immediately on some conditions. If this is the case, then I would suggest some changes in the applied fix:
(2 possible implementations)

- Introduce an `immediateClose` method that will close the popup, well, immediately.
- `close` method should accept an object with `animation` prop. The method will be used like so:
```
  popup.close({ animation: false });
```

I would vote for the second approach, as it is clearer and explicit in its action and in the same time does not bloat the API with additional methods.

Would it be possible to apply that change and push it in the this branch?

**Comment by nlazarov** [comment]
Actually the skipEffects parameter in the close method was there all along. It was not documented for some reason, but seems to be used in the editor and menu widgets.

I am afraid that if I introduce the proposed change, i.e. use the `{animation: false}` option in the `close` method, then I would introduce a change in these widgets as well.

**Comment by ggkrustev** [comment]
Indeed, this seems to be an old solution.
OK, in that case I am fine with the applied changes. I will merge the fix to origin/master branch.

Let me know if you want to cherry-pick those changes in production too.

**Comment by nlazarov** [comment]
Sure it makes sense to have it in production as well.

**Pull request merged**
