### PR TITLE
Complete sv-SE localization

### PR DESCRIPTION
**Pull request by Pher0x**

### CODE REVIEW

**Comment by valchev** [comment]
Hi @Pher0x,

Thanks for your pull request, and for using Kendo UI Core! Before we can review your request, we need to ensure that you’ve followed our contributing guidelines. This means we need you to read and sign our [CLA](http://www.telerik.com/kendo-ui/cla) and fix the jshint errors in sv-SE messages file.

Once you’ve done so and have updated this request, we can move forward.

Thanks again for using (and giving back to) Kendo UI! We look forward to working with you.

**Comment by underlog** [comment]
The Travis build failed due to JSHint errors. The diff is also quite non-descriptive of the changes happened. @Pher0x, may you please address that? Thanks!

**Comment by Pher0x** [comment]
@valchev @underlog It should be fixed now.

**Comment by valchev** [comment]
@Pher0x thank you! You have to also read and sign the Kendo UI [CLA](http://www.telerik.com/kendo-ui/cla).

This step confirms that you've read and acknowledged the legal aspects of your contribution which is why it cannot be skipped.

**Comment by Pher0x** [comment]
@valchev I've accepted the CLA now, and my employer has no policy regarding Open Source contributions (but i asked him if it was okay and he said yes) so i left the "Your employer's policy" field empty.

**Pull request merged**
