### PR TITLE
Updated pt-BR messages

### PR DESCRIPTION
**Pull request by danielwermann**
I have made changes in some sentences.

### CODE REVIEW

**Comment by KirilNN** [comment]
i [name],

Thanks for your pull request, and for using Kendo UI Core! Before we can review your request, we need to ensure that you’ve followed [our contributing guidelines](CONTRIBUTING.md). This means we need you to:

* [ ] Sign our [CLA](http://telerik.com/kendo-u/cla). You can check who signed the CLA here: https://docs.google.com/spreadsheet/ccc?key=0Ai9fmoYa2vAydDJ2RzBERFdfNnlSeDBjQU43ZVJ2WUE&usp=drive_web#gid=0

Once you’ve done so and have updated this request, we can move forward.

Thanks again for using (and giving back to) Kendo UI! We look forward to working with you.

**Comment by regisbsb** [comment]
@danielwermann have you signed?

**Comment by danielwermann** [comment]
Hello everyone. Sorry for the large delay, but yes I already have signed it.

**Comment by KirilNN** [comment]
Thanks @danielwermann!

**Pull request merged**
