### PR TITLE
Changes to translations kendo.messages.de-DE, kendo.messages.de-AT, kendo.messages.de-CH

### PR DESCRIPTION
**Pull request by tipag**
1. Why: There were translations missing for de-DE, de-AT, de-CH. Therefore, the english text was shown.
2. What: Translations for FilterCell, FilterMenu, FilterMultiCheck, Gantt were added. Futhermore, the files contained duplicate translations for TreeList, so the duplicate entry was removed. Since some translations contained missspellings or just didn't seem right for me as a german native speaker, I also have corrected and improved some translation texts.

### CODE REVIEW

**Comment by tsvetomir** [comment]
Hi @tipag,

Thanks for your pull request, and for using Kendo UI Core! Before we can review your request, we need to ensure that you’ve followed our [contributing guidelines](https://github.com/telerik/kendo-ui-core#how-to-contribute). This means we need you to read and sign our [CLA](http://www.telerik.com/kendo-ui/cla). Once you’ve done so we can move forward.

Thanks again for using (and giving back to) Kendo UI!

**Comment by tipag** [comment]
Hi,
I signed the CLA, anything else I need to do?

**Comment by nlazarov** [comment]
Hi, @tipag,

I see that you have used plural in the translation of the filters:

`gleich sind` vs `Ist gleich`.

We prefer to stick to the singular form, because it relates better to comparing every single item when filter is applied. Could you, please, re-word those parts to singular?

As a whole you have done fantastic work. Thank you very much for the efforts.

**Comment by tipag** [comment]
The info text of the filter menu expected the filters to be in plural. Therefore, I changed the info text a little as well as changed the filters to singular as you wished. Now they read like a correct german sentence.

**Comment by nlazarov** [comment]
@tipag - much better. Thank you!

I see that there are merge conflicts in `src/messages/kendo.messages.de-DE.js`. Could you, please, resolve them in another commit before merging?

Thank you for the efforts.

**Comment by tipag** [comment]
Resolved the conflicts. Now I hope the changes can finally be merged into your repository, since we really need these changes for our project.

**Comment by nlazarov** [comment]
Changes merged. Thank you @tipag for the efforts.

**Pull request merged**
