### PR TITLE
Update introduction.md NuGet URL

### PR DESCRIPTION
**Pull request by ishotjr**

### CODE REVIEW

**Comment by KirilNN** [comment]
Hi @ishotjr,

I have updated the link manually and it should be live soon.

Thanks for bringing this up.

**Comment by ishotjr** [comment]
@KirilNN No problem! :bowtie:  Unfortunately, the version of Kendo UI Core there is quite out of date (`2015.2.624` vs. `2015.2.902`). :neutral_face:

**Comment by KirilNN** [comment]
@ishotjr we will try to update it for the next official release

**Comment by ishotjr** [comment]
@KirilNN Awesome! :bowtie: :+1:

**Pull request closed without merging**
