### PR TITLE
Calendar keyboard navigation on Mac OS - handle cmd key

### PR DESCRIPTION
**Pull request by vanagnostos**
Proposed fix for https://github.com/telerik/kendo-ui-core/issues/3993

### CODE REVIEW

**Comment by boyandim** [comment]
Hey @vanagnostos thanks for the patch! Before we can merge this in, we'll need you to sign our [CLA](http://www.telerik.com/kendo-ui/cla). Once that's done, post a comment here and I'll merge the change. :)

**Comment by vanagnostos** [comment]
Hi @boyandim, I signed the CLA. Have a nice day!

**Comment by boyandim** [comment]
Thank you. I tested both fixes and they seem to work fine. Still according to our [contribution guide](https://github.com/telerik/kendo-ui-core/blob/master/CONTRIBUTING.md#3-include-tests-describing-the-bug-or-feature) we ask our contributors to include tests when submitting any changes to the code. Could it be possible to include some tests and check if the fix does not brake any existing test?

**Comment by vanagnostos** [comment]
Hi @boyandim okay, I'll have some time to do that next week ...

**Pull request merged**
