### PR TITLE
Add Stock Chart Data Binding topic

### PR DESCRIPTION
**Pull request by tsvetomir**
Suggestions and edits welcome :)

Closes telerik/kendo-ui-core#1816

### CODE REVIEW

**Comment by dimodi** [comment]
Looks very good :) Two cents:

* if there is a comprehensive snippet for one of the modes, let us include one for the other mode as well
* "talking to the developers" with "you do this..." is not a generally used style in our documentation. I am not against it, let us just decide on a certain style and use it consistently

**Comment by tsvetomir** [comment]
Thanks all! I've updated the wording and added a demo.

**Comment by dmihaylo** [comment]
Hi guys, I made a couple of changes content-wise. Feel free to revert or comment.

**Comment by tsvetomir** [comment]
Thanks!

**Pull request merged**
